2018-02-09 22:30:38,191 ERROR: Exception on /table [GET] [in /home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ff7f/Desktop/microblog/app/routes.py", line 126, in table
    table=table)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ff7f/Desktop/microblog/app/templates/table.html", line 17, in template
    {% endfor %}
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/ff7f/Desktop/microblog/flask/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-02-09 22:32:02,997 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 22:38:55,418 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 22:39:22,332 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 22:39:52,458 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 22:40:03,977 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 23:03:11,804 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 23:06:50,413 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-09 23:55:30,782 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:01:07,677 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:03:52,758 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:22:49,679 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:24:02,698 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:24:52,265 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:27:51,328 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:28:43,121 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:34:01,675 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
2018-02-10 00:34:30,482 INFO: Microblog startup [in /home/ff7f/Desktop/microblog/app/__init__.py:35]
